name             'docker_simple'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures docker_simple'
long_description 'Installs/Configures docker_simple'
version          '0.1.0'
