name             'ab'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ab'
long_description 'Installs/Configures ab'
version          '0.1.0'
