name             'wrk2'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wrk2'
long_description 'Installs/Configures wrk2'
version          '0.1.0'
